//
// unittest_import_lite.pb.h
// 
// Generated by the objc protocol buffer compiler plugin.  DO NOT EDIT!
// source: google/protobuf/unittest_import_lite.proto
//

#import <Foundation/Foundation.h>

#import <ProtocolModels/ProtocolModels.h>

#import "unittest_import_public_lite.pb.h"
// @@protoc_insertion_point(imports)

@class ImportMessageLite;
@class ImportMessageLite_Builder;
@class PublicImportMessageLite;
@class PublicImportMessageLite_Builder;

#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif

typedef NS_ENUM(NSInteger, ImportEnumLite) {
  ImportEnumLiteIMPORTLITEFOO = 7,
  ImportEnumLiteIMPORTLITEBAR = 8,
  ImportEnumLiteIMPORTLITEBAZ = 9,
};

BOOL ImportEnumLiteIsValidValue(ImportEnumLite value);


@interface UnittestImportLiteRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*)registry;
@end


#pragma mark - ImportMessageLite

@interface ImportMessageLite : PBGeneratedMessage

@property (readonly) int32_t d;

- (BOOL)hasD;


- (ImportMessageLite_Builder*)builder;
+ (ImportMessageLite_Builder*)builder;
+ (ImportMessageLite_Builder*)builderWithPrototype:(ImportMessageLite*)prototype;
- (ImportMessageLite_Builder*)toBuilder;

@end


@interface ImportMessageLite_Builder : PBGeneratedMessage_Builder

- (ImportMessageLite*)defaultMessageInstance;

- (ImportMessageLite*)build;
- (ImportMessageLite*)buildPartial;

- (instancetype)mergeFrom:(ImportMessageLite*)other;

- (BOOL)hasD;
- (int32_t)d;
- (instancetype)setD:(int32_t) value;
- (instancetype)clearD;

@end


// @@protoc_insertion_point(global_scope)
