//
// unittest_lite.pb.h
// 
// Generated by the objc protocol buffer compiler plugin.  DO NOT EDIT!
// source: google/protobuf/unittest_lite.proto
//

#import <Foundation/Foundation.h>

#import <ProtocolModels/ProtocolModels.h>

#import "unittest_import_lite.pb.h"
// @@protoc_insertion_point(imports)

@class ForeignMessageLite;
@class ForeignMessageLite_Builder;
@class ImportMessageLite;
@class ImportMessageLite_Builder;
@class OptionalGroup_extension_lite;
@class OptionalGroup_extension_lite_Builder;
@class PublicImportMessageLite;
@class PublicImportMessageLite_Builder;
@class RepeatedGroup_extension_lite;
@class RepeatedGroup_extension_lite_Builder;
@class TestAllExtensionsLite;
@class TestAllExtensionsLite_Builder;
@class TestAllTypesLite;
@class TestAllTypesLite_Builder;
@class TestAllTypesLite_NestedMessage;
@class TestAllTypesLite_NestedMessage_Builder;
@class TestAllTypesLite_OptionalGroup;
@class TestAllTypesLite_OptionalGroup_Builder;
@class TestAllTypesLite_RepeatedGroup;
@class TestAllTypesLite_RepeatedGroup_Builder;
@class TestDeprecatedLite;
@class TestDeprecatedLite_Builder;
@class TestNestedExtensionLite;
@class TestNestedExtensionLite_Builder;
@class TestPackedExtensionsLite;
@class TestPackedExtensionsLite_Builder;
@class TestPackedTypesLite;
@class TestPackedTypesLite_Builder;
@class TestParsingMergeLite;
@class TestParsingMergeLite_Builder;
@class TestParsingMergeLite_OptionalGroup;
@class TestParsingMergeLite_OptionalGroup_Builder;
@class TestParsingMergeLite_RepeatedFieldsGenerator;
@class TestParsingMergeLite_RepeatedFieldsGenerator_Builder;
@class TestParsingMergeLite_RepeatedFieldsGenerator_Group1;
@class TestParsingMergeLite_RepeatedFieldsGenerator_Group1_Builder;
@class TestParsingMergeLite_RepeatedFieldsGenerator_Group2;
@class TestParsingMergeLite_RepeatedFieldsGenerator_Group2_Builder;
@class TestParsingMergeLite_RepeatedGroup;
@class TestParsingMergeLite_RepeatedGroup_Builder;

#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif

typedef NS_ENUM(NSInteger, ForeignEnumLite) {
  ForeignEnumLiteFOREIGNLITEFOO = 4,
  ForeignEnumLiteFOREIGNLITEBAR = 5,
  ForeignEnumLiteFOREIGNLITEBAZ = 6,
};

BOOL ForeignEnumLiteIsValidValue(ForeignEnumLite value);

typedef NS_ENUM(NSInteger, TestAllTypesLite_NestedEnum) {
  TestAllTypesLite_NestedEnumFOO = 1,
  TestAllTypesLite_NestedEnumBAR = 2,
  TestAllTypesLite_NestedEnumBAZ = 3,
};

BOOL TestAllTypesLite_NestedEnumIsValidValue(TestAllTypesLite_NestedEnum value);


@interface UnittestLiteRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*)registry;
+ (PBExtensionField *)optionalInt32ExtensionLite;
+ (PBExtensionField *)optionalInt64ExtensionLite;
+ (PBExtensionField *)optionalUint32ExtensionLite;
+ (PBExtensionField *)optionalUint64ExtensionLite;
+ (PBExtensionField *)optionalSint32ExtensionLite;
+ (PBExtensionField *)optionalSint64ExtensionLite;
+ (PBExtensionField *)optionalFixed32ExtensionLite;
+ (PBExtensionField *)optionalFixed64ExtensionLite;
+ (PBExtensionField *)optionalSfixed32ExtensionLite;
+ (PBExtensionField *)optionalSfixed64ExtensionLite;
+ (PBExtensionField *)optionalFloatExtensionLite;
+ (PBExtensionField *)optionalDoubleExtensionLite;
+ (PBExtensionField *)optionalBoolExtensionLite;
+ (PBExtensionField *)optionalStringExtensionLite;
+ (PBExtensionField *)optionalBytesExtensionLite;
+ (PBExtensionField *)OptionalGroupExtensionLite;
+ (PBExtensionField *)optionalNestedMessageExtensionLite;
+ (PBExtensionField *)optionalForeignMessageExtensionLite;
+ (PBExtensionField *)optionalImportMessageExtensionLite;
+ (PBExtensionField *)optionalNestedEnumExtensionLite;
+ (PBExtensionField *)optionalForeignEnumExtensionLite;
+ (PBExtensionField *)optionalImportEnumExtensionLite;
+ (PBExtensionField *)optionalStringPieceExtensionLite;
+ (PBExtensionField *)optionalCordExtensionLite;
+ (PBExtensionField *)optionalPublicImportMessageExtensionLite;
+ (PBExtensionField *)optionalLazyMessageExtensionLite;
+ (PBExtensionField *)repeatedInt32ExtensionLite;
+ (PBExtensionField *)repeatedInt64ExtensionLite;
+ (PBExtensionField *)repeatedUint32ExtensionLite;
+ (PBExtensionField *)repeatedUint64ExtensionLite;
+ (PBExtensionField *)repeatedSint32ExtensionLite;
+ (PBExtensionField *)repeatedSint64ExtensionLite;
+ (PBExtensionField *)repeatedFixed32ExtensionLite;
+ (PBExtensionField *)repeatedFixed64ExtensionLite;
+ (PBExtensionField *)repeatedSfixed32ExtensionLite;
+ (PBExtensionField *)repeatedSfixed64ExtensionLite;
+ (PBExtensionField *)repeatedFloatExtensionLite;
+ (PBExtensionField *)repeatedDoubleExtensionLite;
+ (PBExtensionField *)repeatedBoolExtensionLite;
+ (PBExtensionField *)repeatedStringExtensionLite;
+ (PBExtensionField *)repeatedBytesExtensionLite;
+ (PBExtensionField *)RepeatedGroupExtensionLite;
+ (PBExtensionField *)repeatedNestedMessageExtensionLite;
+ (PBExtensionField *)repeatedForeignMessageExtensionLite;
+ (PBExtensionField *)repeatedImportMessageExtensionLite;
+ (PBExtensionField *)repeatedNestedEnumExtensionLite;
+ (PBExtensionField *)repeatedForeignEnumExtensionLite;
+ (PBExtensionField *)repeatedImportEnumExtensionLite;
+ (PBExtensionField *)repeatedStringPieceExtensionLite;
+ (PBExtensionField *)repeatedCordExtensionLite;
+ (PBExtensionField *)repeatedLazyMessageExtensionLite;
+ (PBExtensionField *)defaultInt32ExtensionLite;
+ (PBExtensionField *)defaultInt64ExtensionLite;
+ (PBExtensionField *)defaultUint32ExtensionLite;
+ (PBExtensionField *)defaultUint64ExtensionLite;
+ (PBExtensionField *)defaultSint32ExtensionLite;
+ (PBExtensionField *)defaultSint64ExtensionLite;
+ (PBExtensionField *)defaultFixed32ExtensionLite;
+ (PBExtensionField *)defaultFixed64ExtensionLite;
+ (PBExtensionField *)defaultSfixed32ExtensionLite;
+ (PBExtensionField *)defaultSfixed64ExtensionLite;
+ (PBExtensionField *)defaultFloatExtensionLite;
+ (PBExtensionField *)defaultDoubleExtensionLite;
+ (PBExtensionField *)defaultBoolExtensionLite;
+ (PBExtensionField *)defaultStringExtensionLite;
+ (PBExtensionField *)defaultBytesExtensionLite;
+ (PBExtensionField *)defaultNestedEnumExtensionLite;
+ (PBExtensionField *)defaultForeignEnumExtensionLite;
+ (PBExtensionField *)defaultImportEnumExtensionLite;
+ (PBExtensionField *)defaultStringPieceExtensionLite;
+ (PBExtensionField *)defaultCordExtensionLite;
+ (PBExtensionField *)packedInt32ExtensionLite;
+ (PBExtensionField *)packedInt64ExtensionLite;
+ (PBExtensionField *)packedUint32ExtensionLite;
+ (PBExtensionField *)packedUint64ExtensionLite;
+ (PBExtensionField *)packedSint32ExtensionLite;
+ (PBExtensionField *)packedSint64ExtensionLite;
+ (PBExtensionField *)packedFixed32ExtensionLite;
+ (PBExtensionField *)packedFixed64ExtensionLite;
+ (PBExtensionField *)packedSfixed32ExtensionLite;
+ (PBExtensionField *)packedSfixed64ExtensionLite;
+ (PBExtensionField *)packedFloatExtensionLite;
+ (PBExtensionField *)packedDoubleExtensionLite;
+ (PBExtensionField *)packedBoolExtensionLite;
+ (PBExtensionField *)packedEnumExtensionLite;
@end


#pragma mark - TestAllTypesLite

@interface TestAllTypesLite : PBGeneratedMessage

@property (readonly) int32_t optionalInt32;
@property (readonly) int64_t optionalInt64;
@property (readonly) uint32_t optionalUint32;
@property (readonly) uint64_t optionalUint64;
@property (readonly) int32_t optionalSint32;
@property (readonly) int64_t optionalSint64;
@property (readonly) uint32_t optionalFixed32;
@property (readonly) uint64_t optionalFixed64;
@property (readonly) int32_t optionalSfixed32;
@property (readonly) int64_t optionalSfixed64;
@property (readonly) Float32 optionalFloat;
@property (readonly) Float64 optionalDouble;
@property (readonly) BOOL optionalBool;
@property (readonly, strong) NSString * optionalString;
@property (readonly, strong) NSData * optionalBytes;
@property (readonly, strong)  TestAllTypesLite_OptionalGroup* OptionalGroup;
@property (readonly, strong)  TestAllTypesLite_NestedMessage* optionalNestedMessage;
@property (readonly, strong)  ForeignMessageLite* optionalForeignMessage;
@property (readonly, strong)  ImportMessageLite* optionalImportMessage;
@property (readonly) TestAllTypesLite_NestedEnum optionalNestedEnum;
@property (readonly) ForeignEnumLite optionalForeignEnum;
@property (readonly) ImportEnumLite optionalImportEnum;
@property (readonly, strong) NSString * optionalStringPiece;
@property (readonly, strong) NSString * optionalCord;
@property (readonly, strong)  PublicImportMessageLite* optionalPublicImportMessage;
@property (readonly, strong)  TestAllTypesLite_NestedMessage* optionalLazyMessage;
@property (readonly, strong) PBArray * repeatedInt32;
@property (readonly, strong) PBArray * repeatedInt64;
@property (readonly, strong) PBArray * repeatedUint32;
@property (readonly, strong) PBArray * repeatedUint64;
@property (readonly, strong) PBArray * repeatedSint32;
@property (readonly, strong) PBArray * repeatedSint64;
@property (readonly, strong) PBArray * repeatedFixed32;
@property (readonly, strong) PBArray * repeatedFixed64;
@property (readonly, strong) PBArray * repeatedSfixed32;
@property (readonly, strong) PBArray * repeatedSfixed64;
@property (readonly, strong) PBArray * repeatedFloat;
@property (readonly, strong) PBArray * repeatedDouble;
@property (readonly, strong) PBArray * repeatedBool;
@property (readonly, strong) NSArray * repeatedString;
@property (readonly, strong) NSArray * repeatedBytes;
@property (readonly, strong) NSArray *RepeatedGroup;
@property (readonly, strong) NSArray *repeatedNestedMessage;
@property (readonly, strong) NSArray *repeatedForeignMessage;
@property (readonly, strong) NSArray *repeatedImportMessage;
@property (readonly, strong) NSArray *repeatedNestedEnum;
@property (readonly, strong) NSArray *repeatedForeignEnum;
@property (readonly, strong) NSArray *repeatedImportEnum;
@property (readonly, strong) NSArray * repeatedStringPiece;
@property (readonly, strong) NSArray * repeatedCord;
@property (readonly, strong) NSArray *repeatedLazyMessage;
@property (readonly) int32_t defaultInt32;
@property (readonly) int64_t defaultInt64;
@property (readonly) uint32_t defaultUint32;
@property (readonly) uint64_t defaultUint64;
@property (readonly) int32_t defaultSint32;
@property (readonly) int64_t defaultSint64;
@property (readonly) uint32_t defaultFixed32;
@property (readonly) uint64_t defaultFixed64;
@property (readonly) int32_t defaultSfixed32;
@property (readonly) int64_t defaultSfixed64;
@property (readonly) Float32 defaultFloat;
@property (readonly) Float64 defaultDouble;
@property (readonly) BOOL defaultBool;
@property (readonly, strong) NSString * defaultString;
@property (readonly, strong) NSData * defaultBytes;
@property (readonly) TestAllTypesLite_NestedEnum defaultNestedEnum;
@property (readonly) ForeignEnumLite defaultForeignEnum;
@property (readonly) ImportEnumLite defaultImportEnum;
@property (readonly, strong) NSString * defaultStringPiece;
@property (readonly, strong) NSString * defaultCord;

- (BOOL)hasOptionalInt32;
- (BOOL)hasOptionalInt64;
- (BOOL)hasOptionalUint32;
- (BOOL)hasOptionalUint64;
- (BOOL)hasOptionalSint32;
- (BOOL)hasOptionalSint64;
- (BOOL)hasOptionalFixed32;
- (BOOL)hasOptionalFixed64;
- (BOOL)hasOptionalSfixed32;
- (BOOL)hasOptionalSfixed64;
- (BOOL)hasOptionalFloat;
- (BOOL)hasOptionalDouble;
- (BOOL)hasOptionalBool;
- (BOOL)hasOptionalString;
- (BOOL)hasOptionalBytes;
- (BOOL)hasOptionalGroup;
- (BOOL)hasOptionalNestedMessage;
- (BOOL)hasOptionalForeignMessage;
- (BOOL)hasOptionalImportMessage;
- (BOOL)hasOptionalNestedEnum;
- (BOOL)hasOptionalForeignEnum;
- (BOOL)hasOptionalImportEnum;
- (BOOL)hasOptionalStringPiece;
- (BOOL)hasOptionalCord;
- (BOOL)hasOptionalPublicImportMessage;
- (BOOL)hasOptionalLazyMessage;
- (BOOL)hasDefaultInt32;
- (BOOL)hasDefaultInt64;
- (BOOL)hasDefaultUint32;
- (BOOL)hasDefaultUint64;
- (BOOL)hasDefaultSint32;
- (BOOL)hasDefaultSint64;
- (BOOL)hasDefaultFixed32;
- (BOOL)hasDefaultFixed64;
- (BOOL)hasDefaultSfixed32;
- (BOOL)hasDefaultSfixed64;
- (BOOL)hasDefaultFloat;
- (BOOL)hasDefaultDouble;
- (BOOL)hasDefaultBool;
- (BOOL)hasDefaultString;
- (BOOL)hasDefaultBytes;
- (BOOL)hasDefaultNestedEnum;
- (BOOL)hasDefaultForeignEnum;
- (BOOL)hasDefaultImportEnum;
- (BOOL)hasDefaultStringPiece;
- (BOOL)hasDefaultCord;

- (int32_t)repeatedInt32AtIndex:(NSUInteger)index;
- (int64_t)repeatedInt64AtIndex:(NSUInteger)index;
- (uint32_t)repeatedUint32AtIndex:(NSUInteger)index;
- (uint64_t)repeatedUint64AtIndex:(NSUInteger)index;
- (int32_t)repeatedSint32AtIndex:(NSUInteger)index;
- (int64_t)repeatedSint64AtIndex:(NSUInteger)index;
- (uint32_t)repeatedFixed32AtIndex:(NSUInteger)index;
- (uint64_t)repeatedFixed64AtIndex:(NSUInteger)index;
- (int32_t)repeatedSfixed32AtIndex:(NSUInteger)index;
- (int64_t)repeatedSfixed64AtIndex:(NSUInteger)index;
- (Float32)repeatedFloatAtIndex:(NSUInteger)index;
- (Float64)repeatedDoubleAtIndex:(NSUInteger)index;
- (BOOL)repeatedBoolAtIndex:(NSUInteger)index;
- (NSString *)repeatedStringAtIndex:(NSUInteger)index;
- (NSData *)repeatedBytesAtIndex:(NSUInteger)index;
- (TestAllTypesLite_RepeatedGroup*)RepeatedGroupAtIndex:(NSUInteger)index;
- (TestAllTypesLite_NestedMessage*)repeatedNestedMessageAtIndex:(NSUInteger)index;
- (ForeignMessageLite*)repeatedForeignMessageAtIndex:(NSUInteger)index;
- (ImportMessageLite*)repeatedImportMessageAtIndex:(NSUInteger)index;
- (TestAllTypesLite_NestedEnum)repeatedNestedEnumAtIndex:(NSUInteger)index;
- (ForeignEnumLite)repeatedForeignEnumAtIndex:(NSUInteger)index;
- (ImportEnumLite)repeatedImportEnumAtIndex:(NSUInteger)index;
- (NSString *)repeatedStringPieceAtIndex:(NSUInteger)index;
- (NSString *)repeatedCordAtIndex:(NSUInteger)index;
- (TestAllTypesLite_NestedMessage*)repeatedLazyMessageAtIndex:(NSUInteger)index;

- (TestAllTypesLite_Builder*)builder;
+ (TestAllTypesLite_Builder*)builder;
+ (TestAllTypesLite_Builder*)builderWithPrototype:(TestAllTypesLite*)prototype;
- (TestAllTypesLite_Builder*)toBuilder;

@end


@interface TestAllTypesLite_Builder : PBGeneratedMessage_Builder

- (TestAllTypesLite*)defaultMessageInstance;

- (TestAllTypesLite*)build;
- (TestAllTypesLite*)buildPartial;

- (instancetype)mergeFrom:(TestAllTypesLite*)other;

- (BOOL)hasOptionalInt32;
- (int32_t)optionalInt32;
- (instancetype)setOptionalInt32:(int32_t) value;
- (instancetype)clearOptionalInt32;

- (BOOL)hasOptionalInt64;
- (int64_t)optionalInt64;
- (instancetype)setOptionalInt64:(int64_t) value;
- (instancetype)clearOptionalInt64;

- (BOOL)hasOptionalUint32;
- (uint32_t)optionalUint32;
- (instancetype)setOptionalUint32:(uint32_t) value;
- (instancetype)clearOptionalUint32;

- (BOOL)hasOptionalUint64;
- (uint64_t)optionalUint64;
- (instancetype)setOptionalUint64:(uint64_t) value;
- (instancetype)clearOptionalUint64;

- (BOOL)hasOptionalSint32;
- (int32_t)optionalSint32;
- (instancetype)setOptionalSint32:(int32_t) value;
- (instancetype)clearOptionalSint32;

- (BOOL)hasOptionalSint64;
- (int64_t)optionalSint64;
- (instancetype)setOptionalSint64:(int64_t) value;
- (instancetype)clearOptionalSint64;

- (BOOL)hasOptionalFixed32;
- (uint32_t)optionalFixed32;
- (instancetype)setOptionalFixed32:(uint32_t) value;
- (instancetype)clearOptionalFixed32;

- (BOOL)hasOptionalFixed64;
- (uint64_t)optionalFixed64;
- (instancetype)setOptionalFixed64:(uint64_t) value;
- (instancetype)clearOptionalFixed64;

- (BOOL)hasOptionalSfixed32;
- (int32_t)optionalSfixed32;
- (instancetype)setOptionalSfixed32:(int32_t) value;
- (instancetype)clearOptionalSfixed32;

- (BOOL)hasOptionalSfixed64;
- (int64_t)optionalSfixed64;
- (instancetype)setOptionalSfixed64:(int64_t) value;
- (instancetype)clearOptionalSfixed64;

- (BOOL)hasOptionalFloat;
- (Float32)optionalFloat;
- (instancetype)setOptionalFloat:(Float32) value;
- (instancetype)clearOptionalFloat;

- (BOOL)hasOptionalDouble;
- (Float64)optionalDouble;
- (instancetype)setOptionalDouble:(Float64) value;
- (instancetype)clearOptionalDouble;

- (BOOL)hasOptionalBool;
- (BOOL)optionalBool;
- (instancetype)setOptionalBool:(BOOL) value;
- (instancetype)clearOptionalBool;

- (BOOL)hasOptionalString;
- (NSString *)optionalString;
- (instancetype)setOptionalString:(NSString *) value;
- (instancetype)clearOptionalString;

- (BOOL)hasOptionalBytes;
- (NSData *)optionalBytes;
- (instancetype)setOptionalBytes:(NSData *) value;
- (instancetype)clearOptionalBytes;

- (BOOL)hasOptionalGroup;
- (TestAllTypesLite_OptionalGroup*)OptionalGroup;
- (instancetype)setOptionalGroup:(TestAllTypesLite_OptionalGroup*)value;
- (instancetype)setOptionalGroupBuilder:(TestAllTypesLite_OptionalGroup_Builder*)builderForValue;
- (instancetype)mergeOptionalGroup:(TestAllTypesLite_OptionalGroup*)value;
- (instancetype)clearOptionalGroup;

- (BOOL)hasOptionalNestedMessage;
- (TestAllTypesLite_NestedMessage*)optionalNestedMessage;
- (instancetype)setOptionalNestedMessage:(TestAllTypesLite_NestedMessage*)value;
- (instancetype)setOptionalNestedMessageBuilder:(TestAllTypesLite_NestedMessage_Builder*)builderForValue;
- (instancetype)mergeOptionalNestedMessage:(TestAllTypesLite_NestedMessage*)value;
- (instancetype)clearOptionalNestedMessage;

- (BOOL)hasOptionalForeignMessage;
- (ForeignMessageLite*)optionalForeignMessage;
- (instancetype)setOptionalForeignMessage:(ForeignMessageLite*)value;
- (instancetype)setOptionalForeignMessageBuilder:(ForeignMessageLite_Builder*)builderForValue;
- (instancetype)mergeOptionalForeignMessage:(ForeignMessageLite*)value;
- (instancetype)clearOptionalForeignMessage;

- (BOOL)hasOptionalImportMessage;
- (ImportMessageLite*)optionalImportMessage;
- (instancetype)setOptionalImportMessage:(ImportMessageLite*)value;
- (instancetype)setOptionalImportMessageBuilder:(ImportMessageLite_Builder*)builderForValue;
- (instancetype)mergeOptionalImportMessage:(ImportMessageLite*)value;
- (instancetype)clearOptionalImportMessage;

- (BOOL)hasOptionalNestedEnum;
- (TestAllTypesLite_NestedEnum)optionalNestedEnum;
- (instancetype)setOptionalNestedEnum:(TestAllTypesLite_NestedEnum)value;
- (instancetype)clearOptionalNestedEnum;

- (BOOL)hasOptionalForeignEnum;
- (ForeignEnumLite)optionalForeignEnum;
- (instancetype)setOptionalForeignEnum:(ForeignEnumLite)value;
- (instancetype)clearOptionalForeignEnum;

- (BOOL)hasOptionalImportEnum;
- (ImportEnumLite)optionalImportEnum;
- (instancetype)setOptionalImportEnum:(ImportEnumLite)value;
- (instancetype)clearOptionalImportEnum;

- (BOOL)hasOptionalStringPiece;
- (NSString *)optionalStringPiece;
- (instancetype)setOptionalStringPiece:(NSString *) value;
- (instancetype)clearOptionalStringPiece;

- (BOOL)hasOptionalCord;
- (NSString *)optionalCord;
- (instancetype)setOptionalCord:(NSString *) value;
- (instancetype)clearOptionalCord;

- (BOOL)hasOptionalPublicImportMessage;
- (PublicImportMessageLite*)optionalPublicImportMessage;
- (instancetype)setOptionalPublicImportMessage:(PublicImportMessageLite*)value;
- (instancetype)setOptionalPublicImportMessageBuilder:(PublicImportMessageLite_Builder*)builderForValue;
- (instancetype)mergeOptionalPublicImportMessage:(PublicImportMessageLite*)value;
- (instancetype)clearOptionalPublicImportMessage;

- (BOOL)hasOptionalLazyMessage;
- (TestAllTypesLite_NestedMessage*)optionalLazyMessage;
- (instancetype)setOptionalLazyMessage:(TestAllTypesLite_NestedMessage*)value;
- (instancetype)setOptionalLazyMessageBuilder:(TestAllTypesLite_NestedMessage_Builder*)builderForValue;
- (instancetype)mergeOptionalLazyMessage:(TestAllTypesLite_NestedMessage*)value;
- (instancetype)clearOptionalLazyMessage;

- (PBAppendableArray *)repeatedInt32;
- (int32_t)repeatedInt32AtIndex:(NSUInteger)index;
- (instancetype)addRepeatedInt32:(int32_t)value;
- (instancetype)setRepeatedInt32Array:(NSArray *)array;
- (instancetype)setRepeatedInt32Values:(const int32_t *)values count:(NSUInteger)count;
- (instancetype)clearRepeatedInt32;

- (PBAppendableArray *)repeatedInt64;
- (int64_t)repeatedInt64AtIndex:(NSUInteger)index;
- (instancetype)addRepeatedInt64:(int64_t)value;
- (instancetype)setRepeatedInt64Array:(NSArray *)array;
- (instancetype)setRepeatedInt64Values:(const int64_t *)values count:(NSUInteger)count;
- (instancetype)clearRepeatedInt64;

- (PBAppendableArray *)repeatedUint32;
- (uint32_t)repeatedUint32AtIndex:(NSUInteger)index;
- (instancetype)addRepeatedUint32:(uint32_t)value;
- (instancetype)setRepeatedUint32Array:(NSArray *)array;
- (instancetype)setRepeatedUint32Values:(const uint32_t *)values count:(NSUInteger)count;
- (instancetype)clearRepeatedUint32;

- (PBAppendableArray *)repeatedUint64;
- (uint64_t)repeatedUint64AtIndex:(NSUInteger)index;
- (instancetype)addRepeatedUint64:(uint64_t)value;
- (instancetype)setRepeatedUint64Array:(NSArray *)array;
- (instancetype)setRepeatedUint64Values:(const uint64_t *)values count:(NSUInteger)count;
- (instancetype)clearRepeatedUint64;

- (PBAppendableArray *)repeatedSint32;
- (int32_t)repeatedSint32AtIndex:(NSUInteger)index;
- (instancetype)addRepeatedSint32:(int32_t)value;
- (instancetype)setRepeatedSint32Array:(NSArray *)array;
- (instancetype)setRepeatedSint32Values:(const int32_t *)values count:(NSUInteger)count;
- (instancetype)clearRepeatedSint32;

- (PBAppendableArray *)repeatedSint64;
- (int64_t)repeatedSint64AtIndex:(NSUInteger)index;
- (instancetype)addRepeatedSint64:(int64_t)value;
- (instancetype)setRepeatedSint64Array:(NSArray *)array;
- (instancetype)setRepeatedSint64Values:(const int64_t *)values count:(NSUInteger)count;
- (instancetype)clearRepeatedSint64;

- (PBAppendableArray *)repeatedFixed32;
- (uint32_t)repeatedFixed32AtIndex:(NSUInteger)index;
- (instancetype)addRepeatedFixed32:(uint32_t)value;
- (instancetype)setRepeatedFixed32Array:(NSArray *)array;
- (instancetype)setRepeatedFixed32Values:(const uint32_t *)values count:(NSUInteger)count;
- (instancetype)clearRepeatedFixed32;

- (PBAppendableArray *)repeatedFixed64;
- (uint64_t)repeatedFixed64AtIndex:(NSUInteger)index;
- (instancetype)addRepeatedFixed64:(uint64_t)value;
- (instancetype)setRepeatedFixed64Array:(NSArray *)array;
- (instancetype)setRepeatedFixed64Values:(const uint64_t *)values count:(NSUInteger)count;
- (instancetype)clearRepeatedFixed64;

- (PBAppendableArray *)repeatedSfixed32;
- (int32_t)repeatedSfixed32AtIndex:(NSUInteger)index;
- (instancetype)addRepeatedSfixed32:(int32_t)value;
- (instancetype)setRepeatedSfixed32Array:(NSArray *)array;
- (instancetype)setRepeatedSfixed32Values:(const int32_t *)values count:(NSUInteger)count;
- (instancetype)clearRepeatedSfixed32;

- (PBAppendableArray *)repeatedSfixed64;
- (int64_t)repeatedSfixed64AtIndex:(NSUInteger)index;
- (instancetype)addRepeatedSfixed64:(int64_t)value;
- (instancetype)setRepeatedSfixed64Array:(NSArray *)array;
- (instancetype)setRepeatedSfixed64Values:(const int64_t *)values count:(NSUInteger)count;
- (instancetype)clearRepeatedSfixed64;

- (PBAppendableArray *)repeatedFloat;
- (Float32)repeatedFloatAtIndex:(NSUInteger)index;
- (instancetype)addRepeatedFloat:(Float32)value;
- (instancetype)setRepeatedFloatArray:(NSArray *)array;
- (instancetype)setRepeatedFloatValues:(const Float32 *)values count:(NSUInteger)count;
- (instancetype)clearRepeatedFloat;

- (PBAppendableArray *)repeatedDouble;
- (Float64)repeatedDoubleAtIndex:(NSUInteger)index;
- (instancetype)addRepeatedDouble:(Float64)value;
- (instancetype)setRepeatedDoubleArray:(NSArray *)array;
- (instancetype)setRepeatedDoubleValues:(const Float64 *)values count:(NSUInteger)count;
- (instancetype)clearRepeatedDouble;

- (PBAppendableArray *)repeatedBool;
- (BOOL)repeatedBoolAtIndex:(NSUInteger)index;
- (instancetype)addRepeatedBool:(BOOL)value;
- (instancetype)setRepeatedBoolArray:(NSArray *)array;
- (instancetype)setRepeatedBoolValues:(const BOOL *)values count:(NSUInteger)count;
- (instancetype)clearRepeatedBool;

- (NSArray *)repeatedString;
- (NSString *)repeatedStringAtIndex:(NSUInteger)index;
- (instancetype)addRepeatedString:(NSString *)value;
- (instancetype)setRepeatedStringArray:(NSArray *)array;
- (instancetype)clearRepeatedString;

- (NSArray *)repeatedBytes;
- (NSData *)repeatedBytesAtIndex:(NSUInteger)index;
- (instancetype)addRepeatedBytes:(NSData *)value;
- (instancetype)setRepeatedBytesArray:(NSArray *)array;
- (instancetype)clearRepeatedBytes;

- (NSMutableArray *)RepeatedGroup;
- (TestAllTypesLite_RepeatedGroup*)RepeatedGroupAtIndex:(NSUInteger)index;
- (instancetype)addRepeatedGroup:(TestAllTypesLite_RepeatedGroup*)value;
- (instancetype)setRepeatedGroupArray:(NSArray *)array;
- (instancetype)clearRepeatedGroup;

- (NSMutableArray *)repeatedNestedMessage;
- (TestAllTypesLite_NestedMessage*)repeatedNestedMessageAtIndex:(NSUInteger)index;
- (instancetype)addRepeatedNestedMessage:(TestAllTypesLite_NestedMessage*)value;
- (instancetype)setRepeatedNestedMessageArray:(NSArray *)array;
- (instancetype)clearRepeatedNestedMessage;

- (NSMutableArray *)repeatedForeignMessage;
- (ForeignMessageLite*)repeatedForeignMessageAtIndex:(NSUInteger)index;
- (instancetype)addRepeatedForeignMessage:(ForeignMessageLite*)value;
- (instancetype)setRepeatedForeignMessageArray:(NSArray *)array;
- (instancetype)clearRepeatedForeignMessage;

- (NSMutableArray *)repeatedImportMessage;
- (ImportMessageLite*)repeatedImportMessageAtIndex:(NSUInteger)index;
- (instancetype)addRepeatedImportMessage:(ImportMessageLite*)value;
- (instancetype)setRepeatedImportMessageArray:(NSArray *)array;
- (instancetype)clearRepeatedImportMessage;

- (NSMutableArray *)repeatedNestedEnum;
- (TestAllTypesLite_NestedEnum)repeatedNestedEnumAtIndex:(NSUInteger)index;
- (instancetype)addRepeatedNestedEnum:(TestAllTypesLite_NestedEnum)value;
- (instancetype)setRepeatedNestedEnumArray:(NSArray *)array;
- (instancetype)clearRepeatedNestedEnum;

- (NSMutableArray *)repeatedForeignEnum;
- (ForeignEnumLite)repeatedForeignEnumAtIndex:(NSUInteger)index;
- (instancetype)addRepeatedForeignEnum:(ForeignEnumLite)value;
- (instancetype)setRepeatedForeignEnumArray:(NSArray *)array;
- (instancetype)clearRepeatedForeignEnum;

- (NSMutableArray *)repeatedImportEnum;
- (ImportEnumLite)repeatedImportEnumAtIndex:(NSUInteger)index;
- (instancetype)addRepeatedImportEnum:(ImportEnumLite)value;
- (instancetype)setRepeatedImportEnumArray:(NSArray *)array;
- (instancetype)clearRepeatedImportEnum;

- (NSArray *)repeatedStringPiece;
- (NSString *)repeatedStringPieceAtIndex:(NSUInteger)index;
- (instancetype)addRepeatedStringPiece:(NSString *)value;
- (instancetype)setRepeatedStringPieceArray:(NSArray *)array;
- (instancetype)clearRepeatedStringPiece;

- (NSArray *)repeatedCord;
- (NSString *)repeatedCordAtIndex:(NSUInteger)index;
- (instancetype)addRepeatedCord:(NSString *)value;
- (instancetype)setRepeatedCordArray:(NSArray *)array;
- (instancetype)clearRepeatedCord;

- (NSMutableArray *)repeatedLazyMessage;
- (TestAllTypesLite_NestedMessage*)repeatedLazyMessageAtIndex:(NSUInteger)index;
- (instancetype)addRepeatedLazyMessage:(TestAllTypesLite_NestedMessage*)value;
- (instancetype)setRepeatedLazyMessageArray:(NSArray *)array;
- (instancetype)clearRepeatedLazyMessage;

- (BOOL)hasDefaultInt32;
- (int32_t)defaultInt32;
- (instancetype)setDefaultInt32:(int32_t) value;
- (instancetype)clearDefaultInt32;

- (BOOL)hasDefaultInt64;
- (int64_t)defaultInt64;
- (instancetype)setDefaultInt64:(int64_t) value;
- (instancetype)clearDefaultInt64;

- (BOOL)hasDefaultUint32;
- (uint32_t)defaultUint32;
- (instancetype)setDefaultUint32:(uint32_t) value;
- (instancetype)clearDefaultUint32;

- (BOOL)hasDefaultUint64;
- (uint64_t)defaultUint64;
- (instancetype)setDefaultUint64:(uint64_t) value;
- (instancetype)clearDefaultUint64;

- (BOOL)hasDefaultSint32;
- (int32_t)defaultSint32;
- (instancetype)setDefaultSint32:(int32_t) value;
- (instancetype)clearDefaultSint32;

- (BOOL)hasDefaultSint64;
- (int64_t)defaultSint64;
- (instancetype)setDefaultSint64:(int64_t) value;
- (instancetype)clearDefaultSint64;

- (BOOL)hasDefaultFixed32;
- (uint32_t)defaultFixed32;
- (instancetype)setDefaultFixed32:(uint32_t) value;
- (instancetype)clearDefaultFixed32;

- (BOOL)hasDefaultFixed64;
- (uint64_t)defaultFixed64;
- (instancetype)setDefaultFixed64:(uint64_t) value;
- (instancetype)clearDefaultFixed64;

- (BOOL)hasDefaultSfixed32;
- (int32_t)defaultSfixed32;
- (instancetype)setDefaultSfixed32:(int32_t) value;
- (instancetype)clearDefaultSfixed32;

- (BOOL)hasDefaultSfixed64;
- (int64_t)defaultSfixed64;
- (instancetype)setDefaultSfixed64:(int64_t) value;
- (instancetype)clearDefaultSfixed64;

- (BOOL)hasDefaultFloat;
- (Float32)defaultFloat;
- (instancetype)setDefaultFloat:(Float32) value;
- (instancetype)clearDefaultFloat;

- (BOOL)hasDefaultDouble;
- (Float64)defaultDouble;
- (instancetype)setDefaultDouble:(Float64) value;
- (instancetype)clearDefaultDouble;

- (BOOL)hasDefaultBool;
- (BOOL)defaultBool;
- (instancetype)setDefaultBool:(BOOL) value;
- (instancetype)clearDefaultBool;

- (BOOL)hasDefaultString;
- (NSString *)defaultString;
- (instancetype)setDefaultString:(NSString *) value;
- (instancetype)clearDefaultString;

- (BOOL)hasDefaultBytes;
- (NSData *)defaultBytes;
- (instancetype)setDefaultBytes:(NSData *) value;
- (instancetype)clearDefaultBytes;

- (BOOL)hasDefaultNestedEnum;
- (TestAllTypesLite_NestedEnum)defaultNestedEnum;
- (instancetype)setDefaultNestedEnum:(TestAllTypesLite_NestedEnum)value;
- (instancetype)clearDefaultNestedEnum;

- (BOOL)hasDefaultForeignEnum;
- (ForeignEnumLite)defaultForeignEnum;
- (instancetype)setDefaultForeignEnum:(ForeignEnumLite)value;
- (instancetype)clearDefaultForeignEnum;

- (BOOL)hasDefaultImportEnum;
- (ImportEnumLite)defaultImportEnum;
- (instancetype)setDefaultImportEnum:(ImportEnumLite)value;
- (instancetype)clearDefaultImportEnum;

- (BOOL)hasDefaultStringPiece;
- (NSString *)defaultStringPiece;
- (instancetype)setDefaultStringPiece:(NSString *) value;
- (instancetype)clearDefaultStringPiece;

- (BOOL)hasDefaultCord;
- (NSString *)defaultCord;
- (instancetype)setDefaultCord:(NSString *) value;
- (instancetype)clearDefaultCord;

@end


#pragma mark - TestAllTypesLite_NestedMessage

@interface TestAllTypesLite_NestedMessage : PBGeneratedMessage

@property (readonly) int32_t bb;

- (BOOL)hasBb;


- (TestAllTypesLite_NestedMessage_Builder*)builder;
+ (TestAllTypesLite_NestedMessage_Builder*)builder;
+ (TestAllTypesLite_NestedMessage_Builder*)builderWithPrototype:(TestAllTypesLite_NestedMessage*)prototype;
- (TestAllTypesLite_NestedMessage_Builder*)toBuilder;

@end


@interface TestAllTypesLite_NestedMessage_Builder : PBGeneratedMessage_Builder

- (TestAllTypesLite_NestedMessage*)defaultMessageInstance;

- (TestAllTypesLite_NestedMessage*)build;
- (TestAllTypesLite_NestedMessage*)buildPartial;

- (instancetype)mergeFrom:(TestAllTypesLite_NestedMessage*)other;

- (BOOL)hasBb;
- (int32_t)bb;
- (instancetype)setBb:(int32_t) value;
- (instancetype)clearBb;

@end


#pragma mark - TestAllTypesLite_OptionalGroup

@interface TestAllTypesLite_OptionalGroup : PBGeneratedMessage

@property (readonly) int32_t a;

- (BOOL)hasA;


- (TestAllTypesLite_OptionalGroup_Builder*)builder;
+ (TestAllTypesLite_OptionalGroup_Builder*)builder;
+ (TestAllTypesLite_OptionalGroup_Builder*)builderWithPrototype:(TestAllTypesLite_OptionalGroup*)prototype;
- (TestAllTypesLite_OptionalGroup_Builder*)toBuilder;

@end


@interface TestAllTypesLite_OptionalGroup_Builder : PBGeneratedMessage_Builder

- (TestAllTypesLite_OptionalGroup*)defaultMessageInstance;

- (TestAllTypesLite_OptionalGroup*)build;
- (TestAllTypesLite_OptionalGroup*)buildPartial;

- (instancetype)mergeFrom:(TestAllTypesLite_OptionalGroup*)other;

- (BOOL)hasA;
- (int32_t)a;
- (instancetype)setA:(int32_t) value;
- (instancetype)clearA;

@end


#pragma mark - TestAllTypesLite_RepeatedGroup

@interface TestAllTypesLite_RepeatedGroup : PBGeneratedMessage

@property (readonly) int32_t a;

- (BOOL)hasA;


- (TestAllTypesLite_RepeatedGroup_Builder*)builder;
+ (TestAllTypesLite_RepeatedGroup_Builder*)builder;
+ (TestAllTypesLite_RepeatedGroup_Builder*)builderWithPrototype:(TestAllTypesLite_RepeatedGroup*)prototype;
- (TestAllTypesLite_RepeatedGroup_Builder*)toBuilder;

@end


@interface TestAllTypesLite_RepeatedGroup_Builder : PBGeneratedMessage_Builder

- (TestAllTypesLite_RepeatedGroup*)defaultMessageInstance;

- (TestAllTypesLite_RepeatedGroup*)build;
- (TestAllTypesLite_RepeatedGroup*)buildPartial;

- (instancetype)mergeFrom:(TestAllTypesLite_RepeatedGroup*)other;

- (BOOL)hasA;
- (int32_t)a;
- (instancetype)setA:(int32_t) value;
- (instancetype)clearA;

@end


#pragma mark - ForeignMessageLite

@interface ForeignMessageLite : PBGeneratedMessage

@property (readonly) int32_t c;

- (BOOL)hasC;


- (ForeignMessageLite_Builder*)builder;
+ (ForeignMessageLite_Builder*)builder;
+ (ForeignMessageLite_Builder*)builderWithPrototype:(ForeignMessageLite*)prototype;
- (ForeignMessageLite_Builder*)toBuilder;

@end


@interface ForeignMessageLite_Builder : PBGeneratedMessage_Builder

- (ForeignMessageLite*)defaultMessageInstance;

- (ForeignMessageLite*)build;
- (ForeignMessageLite*)buildPartial;

- (instancetype)mergeFrom:(ForeignMessageLite*)other;

- (BOOL)hasC;
- (int32_t)c;
- (instancetype)setC:(int32_t) value;
- (instancetype)clearC;

@end


#pragma mark - TestPackedTypesLite

@interface TestPackedTypesLite : PBGeneratedMessage

@property (readonly, strong) PBArray * packedInt32;
@property (readonly, strong) PBArray * packedInt64;
@property (readonly, strong) PBArray * packedUint32;
@property (readonly, strong) PBArray * packedUint64;
@property (readonly, strong) PBArray * packedSint32;
@property (readonly, strong) PBArray * packedSint64;
@property (readonly, strong) PBArray * packedFixed32;
@property (readonly, strong) PBArray * packedFixed64;
@property (readonly, strong) PBArray * packedSfixed32;
@property (readonly, strong) PBArray * packedSfixed64;
@property (readonly, strong) PBArray * packedFloat;
@property (readonly, strong) PBArray * packedDouble;
@property (readonly, strong) PBArray * packedBool;
@property (readonly, strong) NSArray *packedEnum;


- (int32_t)packedInt32AtIndex:(NSUInteger)index;
- (int64_t)packedInt64AtIndex:(NSUInteger)index;
- (uint32_t)packedUint32AtIndex:(NSUInteger)index;
- (uint64_t)packedUint64AtIndex:(NSUInteger)index;
- (int32_t)packedSint32AtIndex:(NSUInteger)index;
- (int64_t)packedSint64AtIndex:(NSUInteger)index;
- (uint32_t)packedFixed32AtIndex:(NSUInteger)index;
- (uint64_t)packedFixed64AtIndex:(NSUInteger)index;
- (int32_t)packedSfixed32AtIndex:(NSUInteger)index;
- (int64_t)packedSfixed64AtIndex:(NSUInteger)index;
- (Float32)packedFloatAtIndex:(NSUInteger)index;
- (Float64)packedDoubleAtIndex:(NSUInteger)index;
- (BOOL)packedBoolAtIndex:(NSUInteger)index;
- (ForeignEnumLite)packedEnumAtIndex:(NSUInteger)index;

- (TestPackedTypesLite_Builder*)builder;
+ (TestPackedTypesLite_Builder*)builder;
+ (TestPackedTypesLite_Builder*)builderWithPrototype:(TestPackedTypesLite*)prototype;
- (TestPackedTypesLite_Builder*)toBuilder;

@end


@interface TestPackedTypesLite_Builder : PBGeneratedMessage_Builder

- (TestPackedTypesLite*)defaultMessageInstance;

- (TestPackedTypesLite*)build;
- (TestPackedTypesLite*)buildPartial;

- (instancetype)mergeFrom:(TestPackedTypesLite*)other;

- (PBAppendableArray *)packedInt32;
- (int32_t)packedInt32AtIndex:(NSUInteger)index;
- (instancetype)addPackedInt32:(int32_t)value;
- (instancetype)setPackedInt32Array:(NSArray *)array;
- (instancetype)setPackedInt32Values:(const int32_t *)values count:(NSUInteger)count;
- (instancetype)clearPackedInt32;

- (PBAppendableArray *)packedInt64;
- (int64_t)packedInt64AtIndex:(NSUInteger)index;
- (instancetype)addPackedInt64:(int64_t)value;
- (instancetype)setPackedInt64Array:(NSArray *)array;
- (instancetype)setPackedInt64Values:(const int64_t *)values count:(NSUInteger)count;
- (instancetype)clearPackedInt64;

- (PBAppendableArray *)packedUint32;
- (uint32_t)packedUint32AtIndex:(NSUInteger)index;
- (instancetype)addPackedUint32:(uint32_t)value;
- (instancetype)setPackedUint32Array:(NSArray *)array;
- (instancetype)setPackedUint32Values:(const uint32_t *)values count:(NSUInteger)count;
- (instancetype)clearPackedUint32;

- (PBAppendableArray *)packedUint64;
- (uint64_t)packedUint64AtIndex:(NSUInteger)index;
- (instancetype)addPackedUint64:(uint64_t)value;
- (instancetype)setPackedUint64Array:(NSArray *)array;
- (instancetype)setPackedUint64Values:(const uint64_t *)values count:(NSUInteger)count;
- (instancetype)clearPackedUint64;

- (PBAppendableArray *)packedSint32;
- (int32_t)packedSint32AtIndex:(NSUInteger)index;
- (instancetype)addPackedSint32:(int32_t)value;
- (instancetype)setPackedSint32Array:(NSArray *)array;
- (instancetype)setPackedSint32Values:(const int32_t *)values count:(NSUInteger)count;
- (instancetype)clearPackedSint32;

- (PBAppendableArray *)packedSint64;
- (int64_t)packedSint64AtIndex:(NSUInteger)index;
- (instancetype)addPackedSint64:(int64_t)value;
- (instancetype)setPackedSint64Array:(NSArray *)array;
- (instancetype)setPackedSint64Values:(const int64_t *)values count:(NSUInteger)count;
- (instancetype)clearPackedSint64;

- (PBAppendableArray *)packedFixed32;
- (uint32_t)packedFixed32AtIndex:(NSUInteger)index;
- (instancetype)addPackedFixed32:(uint32_t)value;
- (instancetype)setPackedFixed32Array:(NSArray *)array;
- (instancetype)setPackedFixed32Values:(const uint32_t *)values count:(NSUInteger)count;
- (instancetype)clearPackedFixed32;

- (PBAppendableArray *)packedFixed64;
- (uint64_t)packedFixed64AtIndex:(NSUInteger)index;
- (instancetype)addPackedFixed64:(uint64_t)value;
- (instancetype)setPackedFixed64Array:(NSArray *)array;
- (instancetype)setPackedFixed64Values:(const uint64_t *)values count:(NSUInteger)count;
- (instancetype)clearPackedFixed64;

- (PBAppendableArray *)packedSfixed32;
- (int32_t)packedSfixed32AtIndex:(NSUInteger)index;
- (instancetype)addPackedSfixed32:(int32_t)value;
- (instancetype)setPackedSfixed32Array:(NSArray *)array;
- (instancetype)setPackedSfixed32Values:(const int32_t *)values count:(NSUInteger)count;
- (instancetype)clearPackedSfixed32;

- (PBAppendableArray *)packedSfixed64;
- (int64_t)packedSfixed64AtIndex:(NSUInteger)index;
- (instancetype)addPackedSfixed64:(int64_t)value;
- (instancetype)setPackedSfixed64Array:(NSArray *)array;
- (instancetype)setPackedSfixed64Values:(const int64_t *)values count:(NSUInteger)count;
- (instancetype)clearPackedSfixed64;

- (PBAppendableArray *)packedFloat;
- (Float32)packedFloatAtIndex:(NSUInteger)index;
- (instancetype)addPackedFloat:(Float32)value;
- (instancetype)setPackedFloatArray:(NSArray *)array;
- (instancetype)setPackedFloatValues:(const Float32 *)values count:(NSUInteger)count;
- (instancetype)clearPackedFloat;

- (PBAppendableArray *)packedDouble;
- (Float64)packedDoubleAtIndex:(NSUInteger)index;
- (instancetype)addPackedDouble:(Float64)value;
- (instancetype)setPackedDoubleArray:(NSArray *)array;
- (instancetype)setPackedDoubleValues:(const Float64 *)values count:(NSUInteger)count;
- (instancetype)clearPackedDouble;

- (PBAppendableArray *)packedBool;
- (BOOL)packedBoolAtIndex:(NSUInteger)index;
- (instancetype)addPackedBool:(BOOL)value;
- (instancetype)setPackedBoolArray:(NSArray *)array;
- (instancetype)setPackedBoolValues:(const BOOL *)values count:(NSUInteger)count;
- (instancetype)clearPackedBool;

- (NSMutableArray *)packedEnum;
- (ForeignEnumLite)packedEnumAtIndex:(NSUInteger)index;
- (instancetype)addPackedEnum:(ForeignEnumLite)value;
- (instancetype)setPackedEnumArray:(NSArray *)array;
- (instancetype)clearPackedEnum;

@end


#pragma mark - TestAllExtensionsLite

@interface TestAllExtensionsLite : PBExtendableMessage




- (TestAllExtensionsLite_Builder*)builder;
+ (TestAllExtensionsLite_Builder*)builder;
+ (TestAllExtensionsLite_Builder*)builderWithPrototype:(TestAllExtensionsLite*)prototype;
- (TestAllExtensionsLite_Builder*)toBuilder;

@end


@interface TestAllExtensionsLite_Builder : PBExtendableMessage_Builder

- (TestAllExtensionsLite*)defaultMessageInstance;

- (TestAllExtensionsLite*)build;
- (TestAllExtensionsLite*)buildPartial;

- (instancetype)mergeFrom:(TestAllExtensionsLite*)other;

@end


#pragma mark - OptionalGroup_extension_lite

@interface OptionalGroup_extension_lite : PBGeneratedMessage

@property (readonly) int32_t a;

- (BOOL)hasA;


- (OptionalGroup_extension_lite_Builder*)builder;
+ (OptionalGroup_extension_lite_Builder*)builder;
+ (OptionalGroup_extension_lite_Builder*)builderWithPrototype:(OptionalGroup_extension_lite*)prototype;
- (OptionalGroup_extension_lite_Builder*)toBuilder;

@end


@interface OptionalGroup_extension_lite_Builder : PBGeneratedMessage_Builder

- (OptionalGroup_extension_lite*)defaultMessageInstance;

- (OptionalGroup_extension_lite*)build;
- (OptionalGroup_extension_lite*)buildPartial;

- (instancetype)mergeFrom:(OptionalGroup_extension_lite*)other;

- (BOOL)hasA;
- (int32_t)a;
- (instancetype)setA:(int32_t) value;
- (instancetype)clearA;

@end


#pragma mark - RepeatedGroup_extension_lite

@interface RepeatedGroup_extension_lite : PBGeneratedMessage

@property (readonly) int32_t a;

- (BOOL)hasA;


- (RepeatedGroup_extension_lite_Builder*)builder;
+ (RepeatedGroup_extension_lite_Builder*)builder;
+ (RepeatedGroup_extension_lite_Builder*)builderWithPrototype:(RepeatedGroup_extension_lite*)prototype;
- (RepeatedGroup_extension_lite_Builder*)toBuilder;

@end


@interface RepeatedGroup_extension_lite_Builder : PBGeneratedMessage_Builder

- (RepeatedGroup_extension_lite*)defaultMessageInstance;

- (RepeatedGroup_extension_lite*)build;
- (RepeatedGroup_extension_lite*)buildPartial;

- (instancetype)mergeFrom:(RepeatedGroup_extension_lite*)other;

- (BOOL)hasA;
- (int32_t)a;
- (instancetype)setA:(int32_t) value;
- (instancetype)clearA;

@end


#pragma mark - TestPackedExtensionsLite

@interface TestPackedExtensionsLite : PBExtendableMessage




- (TestPackedExtensionsLite_Builder*)builder;
+ (TestPackedExtensionsLite_Builder*)builder;
+ (TestPackedExtensionsLite_Builder*)builderWithPrototype:(TestPackedExtensionsLite*)prototype;
- (TestPackedExtensionsLite_Builder*)toBuilder;

@end


@interface TestPackedExtensionsLite_Builder : PBExtendableMessage_Builder

- (TestPackedExtensionsLite*)defaultMessageInstance;

- (TestPackedExtensionsLite*)build;
- (TestPackedExtensionsLite*)buildPartial;

- (instancetype)mergeFrom:(TestPackedExtensionsLite*)other;

@end


#pragma mark - TestNestedExtensionLite

@interface TestNestedExtensionLite : PBGeneratedMessage




+ (PBExtensionField *)nestedExtension;

- (TestNestedExtensionLite_Builder*)builder;
+ (TestNestedExtensionLite_Builder*)builder;
+ (TestNestedExtensionLite_Builder*)builderWithPrototype:(TestNestedExtensionLite*)prototype;
- (TestNestedExtensionLite_Builder*)toBuilder;

@end


@interface TestNestedExtensionLite_Builder : PBGeneratedMessage_Builder

- (TestNestedExtensionLite*)defaultMessageInstance;

- (TestNestedExtensionLite*)build;
- (TestNestedExtensionLite*)buildPartial;

- (instancetype)mergeFrom:(TestNestedExtensionLite*)other;

@end


#pragma mark - TestDeprecatedLite

@interface TestDeprecatedLite : PBGeneratedMessage

@property (readonly) int32_t deprecatedField;

- (BOOL)hasDeprecatedField;


- (TestDeprecatedLite_Builder*)builder;
+ (TestDeprecatedLite_Builder*)builder;
+ (TestDeprecatedLite_Builder*)builderWithPrototype:(TestDeprecatedLite*)prototype;
- (TestDeprecatedLite_Builder*)toBuilder;

@end


@interface TestDeprecatedLite_Builder : PBGeneratedMessage_Builder

- (TestDeprecatedLite*)defaultMessageInstance;

- (TestDeprecatedLite*)build;
- (TestDeprecatedLite*)buildPartial;

- (instancetype)mergeFrom:(TestDeprecatedLite*)other;

- (BOOL)hasDeprecatedField;
- (int32_t)deprecatedField;
- (instancetype)setDeprecatedField:(int32_t) value;
- (instancetype)clearDeprecatedField;

@end


#pragma mark - TestParsingMergeLite

@interface TestParsingMergeLite : PBExtendableMessage

@property (readonly, strong)  TestAllTypesLite* requiredAllTypes;
@property (readonly, strong)  TestAllTypesLite* optionalAllTypes;
@property (readonly, strong) NSArray *repeatedAllTypes;
@property (readonly, strong)  TestParsingMergeLite_OptionalGroup* OptionalGroup;
@property (readonly, strong) NSArray *RepeatedGroup;

- (BOOL)hasRequiredAllTypes;
- (BOOL)hasOptionalAllTypes;
- (BOOL)hasOptionalGroup;

- (TestAllTypesLite*)repeatedAllTypesAtIndex:(NSUInteger)index;
- (TestParsingMergeLite_RepeatedGroup*)RepeatedGroupAtIndex:(NSUInteger)index;

+ (PBExtensionField *)optionalExt;
+ (PBExtensionField *)repeatedExt;

- (TestParsingMergeLite_Builder*)builder;
+ (TestParsingMergeLite_Builder*)builder;
+ (TestParsingMergeLite_Builder*)builderWithPrototype:(TestParsingMergeLite*)prototype;
- (TestParsingMergeLite_Builder*)toBuilder;

@end


@interface TestParsingMergeLite_Builder : PBExtendableMessage_Builder

- (TestParsingMergeLite*)defaultMessageInstance;

- (TestParsingMergeLite*)build;
- (TestParsingMergeLite*)buildPartial;

- (instancetype)mergeFrom:(TestParsingMergeLite*)other;

- (BOOL)hasRequiredAllTypes;
- (TestAllTypesLite*)requiredAllTypes;
- (instancetype)setRequiredAllTypes:(TestAllTypesLite*)value;
- (instancetype)setRequiredAllTypesBuilder:(TestAllTypesLite_Builder*)builderForValue;
- (instancetype)mergeRequiredAllTypes:(TestAllTypesLite*)value;
- (instancetype)clearRequiredAllTypes;

- (BOOL)hasOptionalAllTypes;
- (TestAllTypesLite*)optionalAllTypes;
- (instancetype)setOptionalAllTypes:(TestAllTypesLite*)value;
- (instancetype)setOptionalAllTypesBuilder:(TestAllTypesLite_Builder*)builderForValue;
- (instancetype)mergeOptionalAllTypes:(TestAllTypesLite*)value;
- (instancetype)clearOptionalAllTypes;

- (NSMutableArray *)repeatedAllTypes;
- (TestAllTypesLite*)repeatedAllTypesAtIndex:(NSUInteger)index;
- (instancetype)addRepeatedAllTypes:(TestAllTypesLite*)value;
- (instancetype)setRepeatedAllTypesArray:(NSArray *)array;
- (instancetype)clearRepeatedAllTypes;

- (BOOL)hasOptionalGroup;
- (TestParsingMergeLite_OptionalGroup*)OptionalGroup;
- (instancetype)setOptionalGroup:(TestParsingMergeLite_OptionalGroup*)value;
- (instancetype)setOptionalGroupBuilder:(TestParsingMergeLite_OptionalGroup_Builder*)builderForValue;
- (instancetype)mergeOptionalGroup:(TestParsingMergeLite_OptionalGroup*)value;
- (instancetype)clearOptionalGroup;

- (NSMutableArray *)RepeatedGroup;
- (TestParsingMergeLite_RepeatedGroup*)RepeatedGroupAtIndex:(NSUInteger)index;
- (instancetype)addRepeatedGroup:(TestParsingMergeLite_RepeatedGroup*)value;
- (instancetype)setRepeatedGroupArray:(NSArray *)array;
- (instancetype)clearRepeatedGroup;

@end


#pragma mark - TestParsingMergeLite_RepeatedFieldsGenerator

@interface TestParsingMergeLite_RepeatedFieldsGenerator : PBGeneratedMessage

@property (readonly, strong) NSArray *field1;
@property (readonly, strong) NSArray *field2;
@property (readonly, strong) NSArray *field3;
@property (readonly, strong) NSArray *Group1;
@property (readonly, strong) NSArray *Group2;
@property (readonly, strong) NSArray *ext1;
@property (readonly, strong) NSArray *ext2;


- (TestAllTypesLite*)field1AtIndex:(NSUInteger)index;
- (TestAllTypesLite*)field2AtIndex:(NSUInteger)index;
- (TestAllTypesLite*)field3AtIndex:(NSUInteger)index;
- (TestParsingMergeLite_RepeatedFieldsGenerator_Group1*)Group1AtIndex:(NSUInteger)index;
- (TestParsingMergeLite_RepeatedFieldsGenerator_Group2*)Group2AtIndex:(NSUInteger)index;
- (TestAllTypesLite*)ext1AtIndex:(NSUInteger)index;
- (TestAllTypesLite*)ext2AtIndex:(NSUInteger)index;

- (TestParsingMergeLite_RepeatedFieldsGenerator_Builder*)builder;
+ (TestParsingMergeLite_RepeatedFieldsGenerator_Builder*)builder;
+ (TestParsingMergeLite_RepeatedFieldsGenerator_Builder*)builderWithPrototype:(TestParsingMergeLite_RepeatedFieldsGenerator*)prototype;
- (TestParsingMergeLite_RepeatedFieldsGenerator_Builder*)toBuilder;

@end


@interface TestParsingMergeLite_RepeatedFieldsGenerator_Builder : PBGeneratedMessage_Builder

- (TestParsingMergeLite_RepeatedFieldsGenerator*)defaultMessageInstance;

- (TestParsingMergeLite_RepeatedFieldsGenerator*)build;
- (TestParsingMergeLite_RepeatedFieldsGenerator*)buildPartial;

- (instancetype)mergeFrom:(TestParsingMergeLite_RepeatedFieldsGenerator*)other;

- (NSMutableArray *)field1;
- (TestAllTypesLite*)field1AtIndex:(NSUInteger)index;
- (instancetype)addField1:(TestAllTypesLite*)value;
- (instancetype)setField1Array:(NSArray *)array;
- (instancetype)clearField1;

- (NSMutableArray *)field2;
- (TestAllTypesLite*)field2AtIndex:(NSUInteger)index;
- (instancetype)addField2:(TestAllTypesLite*)value;
- (instancetype)setField2Array:(NSArray *)array;
- (instancetype)clearField2;

- (NSMutableArray *)field3;
- (TestAllTypesLite*)field3AtIndex:(NSUInteger)index;
- (instancetype)addField3:(TestAllTypesLite*)value;
- (instancetype)setField3Array:(NSArray *)array;
- (instancetype)clearField3;

- (NSMutableArray *)Group1;
- (TestParsingMergeLite_RepeatedFieldsGenerator_Group1*)Group1AtIndex:(NSUInteger)index;
- (instancetype)addGroup1:(TestParsingMergeLite_RepeatedFieldsGenerator_Group1*)value;
- (instancetype)setGroup1Array:(NSArray *)array;
- (instancetype)clearGroup1;

- (NSMutableArray *)Group2;
- (TestParsingMergeLite_RepeatedFieldsGenerator_Group2*)Group2AtIndex:(NSUInteger)index;
- (instancetype)addGroup2:(TestParsingMergeLite_RepeatedFieldsGenerator_Group2*)value;
- (instancetype)setGroup2Array:(NSArray *)array;
- (instancetype)clearGroup2;

- (NSMutableArray *)ext1;
- (TestAllTypesLite*)ext1AtIndex:(NSUInteger)index;
- (instancetype)addExt1:(TestAllTypesLite*)value;
- (instancetype)setExt1Array:(NSArray *)array;
- (instancetype)clearExt1;

- (NSMutableArray *)ext2;
- (TestAllTypesLite*)ext2AtIndex:(NSUInteger)index;
- (instancetype)addExt2:(TestAllTypesLite*)value;
- (instancetype)setExt2Array:(NSArray *)array;
- (instancetype)clearExt2;

@end


#pragma mark - TestParsingMergeLite_RepeatedFieldsGenerator_Group1

@interface TestParsingMergeLite_RepeatedFieldsGenerator_Group1 : PBGeneratedMessage

@property (readonly, strong)  TestAllTypesLite* field1;

- (BOOL)hasField1;


- (TestParsingMergeLite_RepeatedFieldsGenerator_Group1_Builder*)builder;
+ (TestParsingMergeLite_RepeatedFieldsGenerator_Group1_Builder*)builder;
+ (TestParsingMergeLite_RepeatedFieldsGenerator_Group1_Builder*)builderWithPrototype:(TestParsingMergeLite_RepeatedFieldsGenerator_Group1*)prototype;
- (TestParsingMergeLite_RepeatedFieldsGenerator_Group1_Builder*)toBuilder;

@end


@interface TestParsingMergeLite_RepeatedFieldsGenerator_Group1_Builder : PBGeneratedMessage_Builder

- (TestParsingMergeLite_RepeatedFieldsGenerator_Group1*)defaultMessageInstance;

- (TestParsingMergeLite_RepeatedFieldsGenerator_Group1*)build;
- (TestParsingMergeLite_RepeatedFieldsGenerator_Group1*)buildPartial;

- (instancetype)mergeFrom:(TestParsingMergeLite_RepeatedFieldsGenerator_Group1*)other;

- (BOOL)hasField1;
- (TestAllTypesLite*)field1;
- (instancetype)setField1:(TestAllTypesLite*)value;
- (instancetype)setField1Builder:(TestAllTypesLite_Builder*)builderForValue;
- (instancetype)mergeField1:(TestAllTypesLite*)value;
- (instancetype)clearField1;

@end


#pragma mark - TestParsingMergeLite_RepeatedFieldsGenerator_Group2

@interface TestParsingMergeLite_RepeatedFieldsGenerator_Group2 : PBGeneratedMessage

@property (readonly, strong)  TestAllTypesLite* field1;

- (BOOL)hasField1;


- (TestParsingMergeLite_RepeatedFieldsGenerator_Group2_Builder*)builder;
+ (TestParsingMergeLite_RepeatedFieldsGenerator_Group2_Builder*)builder;
+ (TestParsingMergeLite_RepeatedFieldsGenerator_Group2_Builder*)builderWithPrototype:(TestParsingMergeLite_RepeatedFieldsGenerator_Group2*)prototype;
- (TestParsingMergeLite_RepeatedFieldsGenerator_Group2_Builder*)toBuilder;

@end


@interface TestParsingMergeLite_RepeatedFieldsGenerator_Group2_Builder : PBGeneratedMessage_Builder

- (TestParsingMergeLite_RepeatedFieldsGenerator_Group2*)defaultMessageInstance;

- (TestParsingMergeLite_RepeatedFieldsGenerator_Group2*)build;
- (TestParsingMergeLite_RepeatedFieldsGenerator_Group2*)buildPartial;

- (instancetype)mergeFrom:(TestParsingMergeLite_RepeatedFieldsGenerator_Group2*)other;

- (BOOL)hasField1;
- (TestAllTypesLite*)field1;
- (instancetype)setField1:(TestAllTypesLite*)value;
- (instancetype)setField1Builder:(TestAllTypesLite_Builder*)builderForValue;
- (instancetype)mergeField1:(TestAllTypesLite*)value;
- (instancetype)clearField1;

@end


#pragma mark - TestParsingMergeLite_OptionalGroup

@interface TestParsingMergeLite_OptionalGroup : PBGeneratedMessage

@property (readonly, strong)  TestAllTypesLite* optionalGroupAllTypes;

- (BOOL)hasOptionalGroupAllTypes;


- (TestParsingMergeLite_OptionalGroup_Builder*)builder;
+ (TestParsingMergeLite_OptionalGroup_Builder*)builder;
+ (TestParsingMergeLite_OptionalGroup_Builder*)builderWithPrototype:(TestParsingMergeLite_OptionalGroup*)prototype;
- (TestParsingMergeLite_OptionalGroup_Builder*)toBuilder;

@end


@interface TestParsingMergeLite_OptionalGroup_Builder : PBGeneratedMessage_Builder

- (TestParsingMergeLite_OptionalGroup*)defaultMessageInstance;

- (TestParsingMergeLite_OptionalGroup*)build;
- (TestParsingMergeLite_OptionalGroup*)buildPartial;

- (instancetype)mergeFrom:(TestParsingMergeLite_OptionalGroup*)other;

- (BOOL)hasOptionalGroupAllTypes;
- (TestAllTypesLite*)optionalGroupAllTypes;
- (instancetype)setOptionalGroupAllTypes:(TestAllTypesLite*)value;
- (instancetype)setOptionalGroupAllTypesBuilder:(TestAllTypesLite_Builder*)builderForValue;
- (instancetype)mergeOptionalGroupAllTypes:(TestAllTypesLite*)value;
- (instancetype)clearOptionalGroupAllTypes;

@end


#pragma mark - TestParsingMergeLite_RepeatedGroup

@interface TestParsingMergeLite_RepeatedGroup : PBGeneratedMessage

@property (readonly, strong)  TestAllTypesLite* repeatedGroupAllTypes;

- (BOOL)hasRepeatedGroupAllTypes;


- (TestParsingMergeLite_RepeatedGroup_Builder*)builder;
+ (TestParsingMergeLite_RepeatedGroup_Builder*)builder;
+ (TestParsingMergeLite_RepeatedGroup_Builder*)builderWithPrototype:(TestParsingMergeLite_RepeatedGroup*)prototype;
- (TestParsingMergeLite_RepeatedGroup_Builder*)toBuilder;

@end


@interface TestParsingMergeLite_RepeatedGroup_Builder : PBGeneratedMessage_Builder

- (TestParsingMergeLite_RepeatedGroup*)defaultMessageInstance;

- (TestParsingMergeLite_RepeatedGroup*)build;
- (TestParsingMergeLite_RepeatedGroup*)buildPartial;

- (instancetype)mergeFrom:(TestParsingMergeLite_RepeatedGroup*)other;

- (BOOL)hasRepeatedGroupAllTypes;
- (TestAllTypesLite*)repeatedGroupAllTypes;
- (instancetype)setRepeatedGroupAllTypes:(TestAllTypesLite*)value;
- (instancetype)setRepeatedGroupAllTypesBuilder:(TestAllTypesLite_Builder*)builderForValue;
- (instancetype)mergeRepeatedGroupAllTypes:(TestAllTypesLite*)value;
- (instancetype)clearRepeatedGroupAllTypes;

@end


// @@protoc_insertion_point(global_scope)
