//
// unittest_import.pb.h
// 
// Generated by the objc protocol buffer compiler plugin.  DO NOT EDIT!
// source: google/protobuf/unittest_import.proto
//

#import <Foundation/Foundation.h>

#import <ProtocolModels/ProtocolModels.h>

#import "unittest_import_public.pb.h"
// @@protoc_insertion_point(imports)

@class ImportMessage;
@class ImportMessage_Builder;
@class PublicImportMessage;
@class PublicImportMessage_Builder;

#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif

typedef NS_ENUM(NSInteger, ImportEnum) {
  ImportEnumIMPORTFOO = 7,
  ImportEnumIMPORTBAR = 8,
  ImportEnumIMPORTBAZ = 9,
};

BOOL ImportEnumIsValidValue(ImportEnum value);


@interface UnittestImportRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*)registry;
@end


#pragma mark - ImportMessage

@interface ImportMessage : PBGeneratedMessage

@property (readonly) int32_t d;

- (BOOL)hasD;


- (ImportMessage_Builder*)builder;
+ (ImportMessage_Builder*)builder;
+ (ImportMessage_Builder*)builderWithPrototype:(ImportMessage*)prototype;
- (ImportMessage_Builder*)toBuilder;

@end


@interface ImportMessage_Builder : PBGeneratedMessage_Builder

- (ImportMessage*)defaultMessageInstance;

- (ImportMessage*)build;
- (ImportMessage*)buildPartial;

- (instancetype)mergeFrom:(ImportMessage*)other;

- (BOOL)hasD;
- (int32_t)d;
- (instancetype)setD:(int32_t) value;
- (instancetype)clearD;

@end


// @@protoc_insertion_point(global_scope)
