//
// unittest_import_public.pb.h
// 
// Generated by the objc protocol buffer compiler plugin.  DO NOT EDIT!
// source: google/protobuf/unittest_import_public.proto
//

#import <Foundation/Foundation.h>

#import <ProtocolModels/ProtocolModels.h>

// @@protoc_insertion_point(imports)

@class PublicImportMessage;
@class PublicImportMessage_Builder;

#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface UnittestImportPublicRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*)registry;
@end


#pragma mark - PublicImportMessage

@interface PublicImportMessage : PBGeneratedMessage

@property (readonly) int32_t e;

- (BOOL)hasE;


- (PublicImportMessage_Builder*)builder;
+ (PublicImportMessage_Builder*)builder;
+ (PublicImportMessage_Builder*)builderWithPrototype:(PublicImportMessage*)prototype;
- (PublicImportMessage_Builder*)toBuilder;

@end


@interface PublicImportMessage_Builder : PBGeneratedMessage_Builder

- (PublicImportMessage*)defaultMessageInstance;

- (PublicImportMessage*)build;
- (PublicImportMessage*)buildPartial;

- (instancetype)mergeFrom:(PublicImportMessage*)other;

- (BOOL)hasE;
- (int32_t)e;
- (instancetype)setE:(int32_t) value;
- (instancetype)clearE;

@end


// @@protoc_insertion_point(global_scope)
