//
// unittest_no_generic_services.pb.m
// 
// Generated by the objc protocol buffer compiler plugin.  DO NOT EDIT!
// source: google/protobuf/unittest_no_generic_services.proto
//

#import "unittest_no_generic_services.pb.h"

// @@protoc_insertion_point(imports)

@implementation UnittestNoGenericServicesRoot

static PBExtensionField* UnittestNoGenericServicesRoot_testExtension = nil;
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [UnittestNoGenericServicesRoot class]) {
    UnittestNoGenericServicesRoot_testExtension =
      [PBExtensionField extensionWithType:PBExtensionTypeInt32
                            extendedClass:[TestMessage class]
                              fieldNumber:1000
                             defaultValue:@(0)
                      messageOrGroupClass:[NSNumber class]
                               isRepeated:NO
                                 isPacked:NO
                   isMessageSetWireFormat:NO];
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}

+ (void)registerAllExtensions:(PBMutableExtensionRegistry*)registry {
  [registry addExtension:UnittestNoGenericServicesRoot_testExtension];
}

+ (PBExtensionField *)testExtension {
  return UnittestNoGenericServicesRoot_testExtension;
}

@end

BOOL TestEnumIsValidValue(TestEnum value) {
  switch (value) {
    case TestEnumFOO:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - TestMessage

@interface TestMessage ()

@property int32_t a;

@end

@implementation TestMessage {
  BOOL _hasA:1;
}

- (instancetype)init {
  self = [super init];
  if (self == nil) {
    return nil;
  }
    _a = 0;
  return self;
}

+ (instancetype)defaultInstance {
  static id _sharedObject = nil;
  static dispatch_once_t onceToken;
  dispatch_once(&onceToken, ^{
    _sharedObject = [[self alloc] init];
  });
  return _sharedObject;
}

- (BOOL)hasA {
  return !!_hasA;
}
- (void)setHasA:(BOOL)value {
  _hasA = !!value;
}


- (BOOL)isInitialized {
  if (!self.extensionsAreInitialized) {
    return NO;
  }
  return YES;
}

- (void)writeToCodedOutputStream:(PBCodedOutputStream*)output {
  if (self.hasA) {
    [output writeInt32:1 value:self.a];
  }
  [self writeExtensionsToCodedOutputStream:output
                                      from:1000
                                        to:536870912];
  [self.unknownFields writeToCodedOutputStream:output];
}

- (int32_t)serializedSize {
  int32_t size_ = _cachedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasA) {
    size_ += computeInt32Size(1, self.a);
  }
  size_ += [self extensionsSerializedSize];
  size_ += self.unknownFields.serializedSize;
  _cachedSerializedSize = size_;
  return size_;
}


+ (TestMessage_Builder*)builder {
  return [[TestMessage_Builder alloc] init];
}
+ (TestMessage_Builder*)builderWithPrototype:(TestMessage*)prototype {
  return [[TestMessage builder] mergeFrom:prototype];
}
- (TestMessage_Builder*)builder {
  return [TestMessage builder];
}
- (TestMessage_Builder*)toBuilder {
  return [TestMessage builderWithPrototype:self];
}

- (void)writeDescriptionTo:(NSMutableString*)output withIndent:(NSString*)indent {
  NSUInteger listCount; listCount = 0;
  if (self.hasA) {
    [output appendFormat:@"%@%@: %@\n", indent, @"a", @(self.a)];
  }
  [self writeExtensionDescriptionToMutableString:(NSMutableString*)output
                                            from:1000
                                              to:536870912
                                      withIndent:indent];
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}

- (BOOL)isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[TestMessage class]]) {
    return NO;
  }
  TestMessage *otherMessage = other;
  return
      self.hasA == otherMessage.hasA &&
      (!self.hasA || self.a == otherMessage.a) &&
      [self isEqualExtensionsInOther:otherMessage from:1000 to:536870912] &&

      (self.unknownFields == otherMessage.unknownFields ||
       (self.unknownFields != nil &&
       [self.unknownFields isEqual:otherMessage.unknownFields]));
}

- (NSUInteger)hash {
  NSUInteger hashCode; hashCode = 7;
  NSUInteger listCount; listCount = 0;
  if (self.hasA) {
    hashCode = hashCode * 31 + [@(self.a) hash];
  }
  hashCode = hashCode * 31 + [self hashExtensionsFrom:1000 to:536870912];
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}

@end


@implementation TestMessage_Builder {
  TestMessage* _result;
}

- (instancetype)init {
  self = [super init];
  if (self == nil) {
    return nil;
  }
  _result = [[TestMessage alloc] init];
  return self;
}

- (PBExtendableMessage*)internalGetResult {
  return _result;
}
- (instancetype)clear {
  _result = [[TestMessage alloc] init];
  return self;
}
- (instancetype)clone {
  return [[[TestMessage_Builder alloc] init] mergeFrom:_result];
}

- (TestMessage*)defaultMessageInstance {
  return [TestMessage defaultInstance];
}

- (TestMessage*)build {
  [self checkInitialized];
  return [self buildPartial];
}
- (TestMessage*)buildPartial {
  TestMessage* partial = _result;
  _result = nil;
  return partial;
}

- (instancetype)mergeFrom:(TestMessage*)other {
  if (other == [TestMessage defaultInstance]) {
    return self;
  }
  if (other.hasA) {
    [self setA:other.a];
  }
  [self mergeExtensionFields:other];
  [self mergeUnknownFields:other.unknownFields];
  return self;
}

- (instancetype)mergeFromCodedInputStream:(PBCodedInputStream*)input
                        extensionRegistry:(PBExtensionRegistry*)extensionRegistry
{
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input
                       unknownFields:unknownFields
                   extensionRegistry:extensionRegistry
                                 tag:tag])
        {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setA:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL)hasA {
  return _result.hasA;
}
- (int32_t) a {
  return _result.a;
}
- (instancetype)setA:(int32_t)value {
  _result.hasA = YES;
  _result.a = value;
  return self;
}
- (instancetype)clearA {
  _result.hasA = NO;
  _result.a = 0;
  return self;
}

@end


// @@protoc_insertion_point(global_scope)
